services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data
  maps-house:
    ports:
      - 7777:8080
    env_file:
      - ./app.env
    environment:
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
    container_name: maps-house
    image: 'xxdstem/maps-house:latest'
volumes:
  postgres: